version: '3.0'
services:
  node0:
    build:
      context: .
      args:
        - NAME=0
    volumes: 
      - ./export:/export
      - .:/app
  node1:
    build:
      context: .
      args:
        - NAME=1
    volumes:
      - ./export:/export
      - .:/app
  node2:
    build:
      context: .
      args:
        - NAME=2
    volumes:
      - ./export:/export
      - .:/app
  node3:
    build:
      context: .
      args:
        - NAME=3
    volumes:
      - ./export:/export
      - .:/app
  node4:
    build:
      context: .
      args:
        - NAME=4
    volumes:
      - ./export:/export
      - .:/app
  node5:
    build:
      context: .
      args:
        - NAME=5
    volumes:
      - ./export:/export
      - .:/app
  node6:
    build:
      context: .
      args:
        - NAME=6
    volumes:
      - ./export:/export
      - .:/app
  node7:
    build:
      context: .
      args:
        - NAME=7
    volumes:
      - ./export:/export
      - .:/app
  node8:
    build:
      context: .
      args:
        - NAME=8
    volumes:
      - ./export:/export
      - .:/app
  node9:
    build:
      context: .
      args:
        - NAME=9
    volumes:
      - ./export:/export
      - .:/app