POST http://localhost:5000/register
json({
	"pgp":"
-----BEGIN PGP PUBLIC KEY BLOCK-----
mQENBGCNfg4BCAC887+7jSE/HYy33B1i9qALH2KR0DbKMNlmsV2OMAej2OjtSbbm
va6Bi91Xy+4ti/In2hIICG/cdJDfa4YxCywIVrbvto+Gd8xl9Y8m7J0SC10tM9O/
MfHo3Q+Vcfod3o0A1i+hXTUzT1Sluo9Z0IztXhPRFLWnuKP8HKwNo8VYgyZnBhNs
TxDEdlO1QvCrzo7o7lWzJei+mABYNgIg6frLNdzAC6qZuF4lRx7qG/y/Qg2wFTAC
xAAEPlU2h85EpD5RBSqQtDNTe6DDKfuTqsrbpy1mkEFv4dm/Jz1249zu1vyAjtv6
4l3cqAEW6bu4cnmz8QAZK6p600u7MmCaChbXABEBAAG0JkF1dG9nZW5lcmF0ZWQg
S2V5IDxjbGllbnRAZG90aHR0cC5kZXY+iQFOBBMBCgA4FiEELV+ouFF9alVc94XM
mFbE7FHya2IFAmCNfg4CGy8FCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQmFbE
7FHya2LEywf/VSOYP6A0/ihlJPrgGga9W8SKSqXJvKQnCZ5FXeK9kfOPtZ2Pt7wf
oIW0ZfJlBCxDsjnnM6uKw1Tsc0qXnXMQ9P+ZMw/E0t29RhP7r6c+/c+DceBPKjV1
ayMFc5h04KSY/2A0nj/PIk7awW4PP8mBc7VNgXCMSJt0TH5F+fK9R0J6RIyockCN
dwG6DuHBRNyGeOjZ3XgPkEFfc6Iz/H7E8lG1w8+3FBc2sHw0N9Bp3DDSi026GIqE
tp32e12Unez0rMYAzeYMGG+7UVGkXv534324YTDa/Mfes8WKbuiCFMk38gOZkvgP
8INchY+j07t7zA1y9P3SFTPmtu52OM860w==
=MxLx
-----END PGP PUBLIC KEY BLOCK-----
"})

POST "http://localhost:5000/message"
json({
	"message": '
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

test
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEE8HTY7/b0ss+ssQBknJZQE9HzjaoFAmCN/wgACgkQnJZQE9Hz
japonwf9FUKeKxXEzEHiHD8eIXe92G7qTo9EfsTGFDLGKM0BiMApKZJpOs3wZfnV
mdcr6HJrM8uDioO2mcpu2CyqcHR/01iVB82MSv/cBzDUzV3u6SEn1EuNzAmixqLY
cJvcgA6Ur9sIdHDZE0rACTXV7NQvxXpoYgTvZM2lbPImfVr36Vrei2oDAfs7y01v
mcOTVTfLuqaNX3Ok1q7PuxfGNFMpRUhthnrqIQHpgRfH/KCkOnIwLX4qa41AjHHb
F/pSfsjlUzcP10ctM5pzmJN9UFGKGpn4xpiZHFsOy39cSEYgGnPodJA16/GMw+sU
iJ5KVXQCtky5gu/sI5ye/gHajSFerA==
=eVyq
-----END PGP SIGNATURE-----'
})



@name('count of blocks')
GET "http://localhost:5000/block/count"


@name('get latest block hash')
GET "http://localhost:5000/block/latest"



@name('list blocks available')
GET "http://localhost:5000/block/list"



# not working
@name('get previous block')
GET "http://localhost:5000/block/previous/6f3459326940dfe6f4a01425ca05907d83b2bb56cee8ff41215a0cc8d6aa1359"

@name('get specific block')
GET "http://localhost:5000/block/6f3459326940dfe6f4a01425ca05907d83b2bb56cee8ff41215a0cc8d6aa1359"



@name('get by  index')
GET "http://localhost:5000/block/index/2"